### ISSUE TITLE
Creating Language Profiles

### ISSUE THREAD

**Issue by karir04** [shuyo/language-detection#82]
Hi,
I really need to make use of this library for an important school project.

What I am wondering is if I can add more language profiles? If so, how can I do this?

Thanks

**Comment by gyscos** [comment]
https://github.com/shuyo/language-detection/blob/wiki/Tools.md

**Comment by dansupriti** [comment]
Hi @karir04 
Are you able to add new language profiles? if so kindly help me with the steps?

**Comment by Pukimaa** [comment]
When trying to generate a new profile I get the following error:
```
> java -jar langdetect.jar --genprofile -d dewiki-20221201-abstract.xml.gz de
Exception in thread "main" java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

Caused by: java.lang.NullPointerException
    at com.cybozu.labs.langdetect.Command.searchFile(Command.java:93)
    at com.cybozu.labs.langdetect.Command.generateProfile(Command.java:128)
    at com.cybozu.labs.langdetect.Command.main(Command.java:325)
... 5 more
```
